package com.youhuo.pojo;

/**
 * ATTR_VALUE
 * 
 * @author sunrise
 * @version 1.0.0 2019-11-23
 */
public class AttrValue implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4506345062096021138L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 属性值ID */
    private Integer attrvId;

    /** 属性值 */
    private String attrValue;

    /** 属性名ID */
    private Integer attrId;

   public AttrValue() {
	// TODO Auto-generated constructor stub
   }
   
    public AttrValue(Integer attrvId, String attrValue, Integer attrId) {
	super();
	this.attrvId = attrvId;
	this.attrValue = attrValue;
	this.attrId = attrId;
}

	/**
     * 获取属性值ID
     * 
     * @return 属性值ID
     */
    public Integer getAttrvId() {
        return this.attrvId;
    }

    /**
     * 设置属性值ID
     * 
     * @param attrvId
     *          属性值ID
     */
    public void setAttrvId(Integer attrvId) {
        this.attrvId = attrvId;
    }

    /**
     * 获取属性值
     * 
     * @return 属性值
     */
    public String getAttrValue() {
        return this.attrValue;
    }

    /**
     * 设置属性值
     * 
     * @param attrValue
     *          属性值
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }

    /**
     * 获取属性名ID
     * 
     * @return 属性名ID
     */
    public Integer getAttrId() {
        return this.attrId;
    }

    /**
     * 设置属性名ID
     * 
     * @param attrId
     *          属性名ID
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

	@Override
	public String toString() {
		return "AttrValue [attrvId=" + attrvId + ", attrValue=" + attrValue + ", attrId=" + attrId + "]";
	}
    
}