package com.youhuo.pojo;

/**
 * ATTR_NAME
 * 
 * @author sunrise
 * @version 1.0.0 2019-11-23
 */
public class AttrName implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8968324932201610013L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 属性名编号 */
    private Integer attrnId;

    /** 属性名 */
    private String attrName;

    /** 分类编号 */
    private Integer typeId;

    /** 属性父类id 一级属性为0 */
    private Integer parentId;

    public AttrName() {
		// TODO Auto-generated constructor stub
	}
    
    public AttrName(Integer attrnId, String attrName, Integer typeId, Integer parentId) {
		super();
		this.attrnId = attrnId;
		this.attrName = attrName;
		this.typeId = typeId;
		this.parentId = parentId;
	}

	/**
     * 获取属性名编号
     * 
     * @return 属性名编号
     */
    public final Integer getAttrnId() {
        return this.attrnId;
    }

    /**
     * 设置属性名编号
     * 
     * @param attrnId
     *          属性名编号
     */
    public final void setAttrnId(Integer attrnId) {
        this.attrnId = attrnId;
    }

    /**
     * 获取属性名
     * 
     * @return 属性名
     */
    public final String getAttrName() {
        return this.attrName;
    }

    /**
     * 设置属性名
     * 
     * @param attrName
     *          属性名
     */
    public final void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * 获取分类编号
     * 
     * @return 分类编号
     */
    public final Integer getTypeId() {
        return this.typeId;
    }

    /**
     * 设置分类编号
     * 
     * @param typeId
     *          分类编号
     */
    public final void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * 获取属性父类id 一级属性为0
     * 
     * @return 属性父类id 一级属性为0
     */
    public final Integer getParentId() {
        return this.parentId;
    }

    /**
     * 设置属性父类id 一级属性为0
     * 
     * @param parentId
     *          属性父类id 一级属性为0
     */
    public final void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

	@Override
	public String toString() {
		return "AttrName [attrnId=" + attrnId + ", attrName=" + attrName + ", typeId=" + typeId + ", parentId="
				+ parentId + "]";
	}
    
}