/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.0.0
 */
package com.youhuo.pojo;

/**
 * YH_GOODS_TYPE
 * 
 * @author sunrise
 * @version 1.0.0 2019-11-23
 */
public class GoodsType implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7028645071784357477L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 商品类型ID */
    private Integer tyId;

    /** 商品类型名 */
    private String catName;

    /** 商品类型code */
    private String catCode;

    /** 父类id */
    private Integer parentId;

    /** 商品类型图片，一级分类为空 */
    private String catImg;

    /** 备用字段 */
    private String value;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取商品类型ID
     * 
     * @return 商品类型ID
     */
    public Integer getTyId() {
        return this.tyId;
    }

    /**
     * 设置商品类型ID
     * 
     * @param tyId
     *          商品类型ID
     */
    public void setTyId(Integer tyId) {
        this.tyId = tyId;
    }

    /**
     * 获取商品类型名
     * 
     * @return 商品类型名
     */
    public String getCatName() {
        return this.catName;
    }

    /**
     * 设置商品类型名
     * 
     * @param catName
     *          商品类型名
     */
    public void setCatName(String catName) {
        this.catName = catName;
    }

    /**
     * 获取商品类型code
     * 
     * @return 商品类型code
     */
    public String getCatCode() {
        return this.catCode;
    }

    /**
     * 设置商品类型code
     * 
     * @param catCode
     *          商品类型code
     */
    public void setCatCode(String catCode) {
        this.catCode = catCode;
    }

    /**
     * 获取父类id
     * 
     * @return 父类id
     */
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * 设置父类id
     * 
     * @param parentId
     *          父类id
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取商品类型图片，一级分类为空
     * 
     * @return 商品类型图片
     */
    public String getCatImg() {
        return this.catImg;
    }

    /**
     * 设置商品类型图片，一级分类为空
     * 
     * @param catImg
     *          商品类型图片
     */
    public void setCatImg(String catImg) {
        this.catImg = catImg;
    }

    /**
     * 获取备用字段
     * 
     * @return 备用字段
     */
    public String getValue() {
        return this.value;
    }

    /**
     * 设置备用字段
     * 
     * @param value
     *          备用字段
     */
    public void setValue(String value) {
        this.value = value;
    }

	@Override
	public String toString() {
		return "GoodsType [tyId=" + tyId + ", catName=" + catName + ", catCode=" + catCode + ", parentId=" + parentId
				+ ", catImg=" + catImg + ", value=" + value + "]";
	}
    
}