
 package com.youhuo.pojo;

public class OrderInfo implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1238308658742726883L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 订单表id */
    private Long ordId;

    /** 订单编号 */
    private String ordListName;

    /** 收货地址id */
    private Long addressId;

    /** 订单总金额 */
    private Double ordSummoney;

    /** 快递金额(如果为空则是包邮) */
    private Double ordTranMoney;

    /** 订单状态(1.支付成功 2.未支付，0.取消订单) */
    private Integer ordStatus;

    /** 买家留言 */
    private String ordRemaeks;

    /** 快递名 */
    private String ordExpress;
    
    /**发货状态*/
    private int  ordDeliveryStatus;
    
	/** 用户id */
    private String userId;

    /** 订单创建时间 */
    private String created;

    /** 备用字段 */
    private String value;

    public OrderInfo() {
		// TODO Auto-generated constructor stub
	}
    
    public OrderInfo(Long ordId, String ordListName, Long addressId, Double ordSummoney, Double ordTranMoney,
			Integer ordStatus, String ordRemaeks, String ordExpress, int ordDeliveryStatus, String userId,
			String created, String value) {
		this.ordId = ordId;
		this.ordListName = ordListName;
		this.addressId = addressId;
		this.ordSummoney = ordSummoney;
		this.ordTranMoney = ordTranMoney;
		this.ordStatus = ordStatus;
		this.ordRemaeks = ordRemaeks;
		this.ordExpress = ordExpress;
		this.ordDeliveryStatus = ordDeliveryStatus;
		this.userId = userId;
		this.created = created;
		this.value = value;
	}

	/**
     * 获取订单表id
     * 
     * @return 订单表id
     */
    public Long getOrdId() {
        return this.ordId;
    }

    /**
     * 设置订单表id
     * 
     * @param ordId
     *          订单表id
     */
    public void setOrdId(Long ordId) {
        this.ordId = ordId;
    }

    /**
     * 获取订单编号
     * 
     * @return 订单编号
     */
    public String getOrdListName() {
        return this.ordListName;
    }

    /**
     * 设置订单编号
     * 
     * @param ordListName
     *          订单编号
     */
    public void setOrdListName(String ordListName) {
        this.ordListName = ordListName;
    }

    /**
     * 获取收货地址id
     * 
     * @return 收货地址id
     */
    public Long getAddressId() {
        return this.addressId;
    }

    /**
     * 设置收货地址id
     * 
     * @param addressId
     *          收货地址id
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * 获取订单总金额
     * 
     * @return 订单总金额
     */
    public Double getOrdSummoney() {
        return this.ordSummoney;
    }

    /**
     * 设置订单总金额
     * 
     * @param ordSummoney
     *          订单总金额
     */
    public void setOrdSummoney(Double ordSummoney) {
        this.ordSummoney = ordSummoney;
    }

    /**
     * 获取快递金额(如果为空则是包邮)
     * 
     * @return 快递金额(如果为空则是包邮)
     */
    public Double getOrdTranMoney() {
        return this.ordTranMoney;
    }

    /**
     * 设置快递金额(如果为空则是包邮)
     * 
     * @param ordTranMoney
     *          快递金额(如果为空则是包邮)
     */
    public void setOrdTranMoney(Double ordTranMoney) {
        this.ordTranMoney = ordTranMoney;
    }

    /**
     * 获取订单状态(1.支付成功 2.未支付，0.取消订单)
     * 
     * @return 订单状态(1.支付成功 2.未支付
     */
    public Integer getOrdStatus() {
        return this.ordStatus;
    }

    /**
     * 设置订单状态(1.支付成功 2.未支付，0.取消订单)
     * 
     * @param ordStatus
     *          订单状态(1.支付成功 2.未支付
     */
    public void setOrdStatus(Integer ordStatus) {
        this.ordStatus = ordStatus;
    }

    /**
     * 获取买家留言
     * 
     * @return 买家留言
     */
    public String getOrdRemaeks() {
        return this.ordRemaeks;
    }

    /**
     * 设置买家留言
     * 
     * @param ordRemaeks
     *          买家留言
     */
    public void setOrdRemaeks(String ordRemaeks) {
        this.ordRemaeks = ordRemaeks;
    }

    /**
     * 获取快递名
     * 
     * @return 快递名
     */
    public String getOrdExpress() {
        return this.ordExpress;
    }

    /**
     * 设置快递名
     * 
     * @param ordExpress
     *          快递名
     */
    public void setOrdExpress(String ordExpress) {
        this.ordExpress = ordExpress;
    }
    /**
	     * 获得订单状态
	* @return
	*/
    public final int getOrdDeliveryStatus() {
		return ordDeliveryStatus;
	}
    /**
	     * 设置订单状态
	* @return
	*/
	public final void setOrdDeliveryStatus(int ordDeliveryStatus) {
		this.ordDeliveryStatus = ordDeliveryStatus;
	}
    /**
     * 获取用户id
     * 
     * @return 用户id
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * 设置用户id
     * 
     * @param userId
     *          用户id
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * 获取订单创建时间
     * 
     * @return 订单创建时间
     */
    public String getCreated() {
        return this.created;
    }

    /**
     * 设置订单创建时间
     * 
     * @param created
     *          订单创建时间
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     * 获取备用字段
     * 
     * @return 备用字段
     */
    public String getValue() {
        return this.value;
    }

    /**
     * 设置备用字段
     * 
     * @param value
     *          备用字段
     */
    public void setValue(String value) {
        this.value = value;
    }

	@Override
	public String toString() {
		return "Orderinfo [ordId=" + ordId + ", ordListName=" + ordListName + ", addressId=" + addressId
				+ ", ordSummoney=" + ordSummoney + ", ordTranMoney=" + ordTranMoney + ", ordStatus=" + ordStatus
				+ ", ordRemaeks=" + ordRemaeks + ", ordExpress=" + ordExpress + ", userId=" + userId + ", created="
				+ created + ", value=" + value + "]";
	}
    
}