package com.youhuo.pojo;

/**
 * YH_SHOPPINGCAR
 * 
 * @author sunrise
 * @version 1.0.0 2019-11-23
 */
public class ShoppingCar implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -776681649815277320L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 购物车ID */
    private Long carId;

    /** 购物车与商品的关系 */
    private Long listId;

    /** 用户ID */
    private String userId;

    /** 备用字段 */
    private String value;

    public ShoppingCar() {
		// TODO Auto-generated constructor stub
	}
    
    public ShoppingCar(Long carId, Long listId, String userId, String value) {
		super();
		this.carId = carId;
		this.listId = listId;
		this.userId = userId;
		this.value = value;
	}

	/**
     * 获取购物车ID
     * 
     * @return 购物车ID
     */
    public Long getCarId() {
        return this.carId;
    }

    /**
     * 设置购物车ID
     * 
     * @param carId
     *          购物车ID
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }

    /**
     * 获取购物车与商品的关系
     * 
     * @return 购物车与商品的关系
     */
    public Long getListId() {
        return this.listId;
    }

    /**
     * 设置购物车与商品的关系
     * 
     * @param listId
     *          购物车与商品的关系
     */
    public void setListId(Long listId) {
        this.listId = listId;
    }

    /**
     * 获取用户ID
     * 
     * @return 用户ID
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * 设置用户ID
     * 
     * @param userId
     *          用户ID
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * 获取备用字段
     * 
     * @return 备用字段
     */
    public String getValue() {
        return this.value;
    }

    /**
     * 设置备用字段
     * 
     * @param value
     *          备用字段
     */
    public void setValue(String value) {
        this.value = value;
    }

	@Override
	public String toString() {
		return "Shoppingcar [carId=" + carId + ", listId=" + listId + ", userId=" + userId + ", value=" + value + "]";
	}
    
}