package com.youhuo.pojo;

/**
 * SKU_REPERTORY
 * 
 * @author sunrise
 * @version 1.0.0 2019-11-23
 */
public class SkuRepertory implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 8782213078511275815L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** SKU编号 */
    private long skuRepertoryId;

    /** 商品ID */
    private long goodsId;

    /** SKU属性 */
    private String skuAttr;

    /** 价格 */
    private Double price;

    /** 库存 */
    private Integer repertory;

    /** 销量 */
    private Integer skuSel;

    public SkuRepertory() {
		// TODO Auto-generated constructor stub
	}
    
    public SkuRepertory(long skuRepertoryId, long goodsId, String skuAttr, Double price, Integer repertory,
			Integer skuSel) {
		super();
		this.skuRepertoryId = skuRepertoryId;
		this.goodsId = goodsId;
		this.skuAttr = skuAttr;
		this.price = price;
		this.repertory = repertory;
		this.skuSel = skuSel;
	}

	/**
     * 获取SKU编号
     * 
     * @return SKU编号
     */
    public long getSkuRepertoryId() {
        return this.skuRepertoryId;
    }

    /**
     * 设置SKU编号
     * 
     * @param skuRepertoryId
     *          SKU编号
     */
    public void setSkuRepertoryId(long skuRepertoryId) {
        this.skuRepertoryId = skuRepertoryId;
    }

    /**
     * 获取商品ID
     * 
     * @return 商品ID
     */
    public long getGoodsId() {
        return this.goodsId;
    }

    /**
     * 设置商品ID
     * 
     * @param goodsId
     *          商品ID
     */
    public void setGoodsId(long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * 获取SKU属性
     * 
     * @return SKU属性
     */
    public String getSkuAttr() {
        return this.skuAttr;
    }

    /**
     * 设置SKU属性
     * 
     * @param skuAttr
     *          SKU属性
     */
    public void setSkuAttr(String skuAttr) {
        this.skuAttr = skuAttr;
    }

    /**
     * 获取价格
     * 
     * @return 价格
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * 设置价格
     * 
     * @param price
     *          价格
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * 获取库存
     * 
     * @return 库存
     */
    public Integer getRepertory() {
        return this.repertory;
    }

    /**
     * 设置库存
     * 
     * @param repertory
     *          库存
     */
    public void setRepertory(Integer repertory) {
        this.repertory = repertory;
    }

    /**
     * 获取销量
     * 
     * @return 销量
     */
    public Integer getSkuSel() {
        return this.skuSel;
    }

    /**
     * 设置销量
     * 
     * @param skuSel
     *          销量
     */
    public void setSkuSel(Integer skuSel) {
        this.skuSel = skuSel;
    }

	@Override
	public String toString() {
		return "SkuRepertory [skuRepertoryId=" + skuRepertoryId + ", goodsId=" + goodsId + ", skuAttr=" + skuAttr
				+ ", price=" + price + ", repertory=" + repertory + ", skuSel=" + skuSel + "]";
	}
    
}