package com.youhuo.pojo;

/**
 * YH_USER
 * 
 * @author sunrise
 * @version 1.0.0 2019-11-23
 */
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4192658980073828705L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 用户id(UUID) */
    private String id;

    /** 用户名不能重复 */
    private String userName;

    /** 用户密码 */
    private String userPass;

    /** 生日 */
    private String userBirthday;

    /** 性别 */
    private Integer sex;

    /** 用户手机号码 */
    private String phone;

    /** 用户邮箱 */
    private String email;

    /** 用户类型为1 管理员为999 */
    private Integer userType;

    /** 用户头像 */
    private String userImg;

    /** 用户密保问题 */
    private Integer questionId;

    /** 用户密保答案 */
    private String questionAnswer;

    /** 用户购物车id */
    private Long carId;

    /** 用户创建时间 */
    private String created;

    /** 备用字段 */
    private String newvalue;

    public User() {
		// TODO Auto-generated constructor stub
	}
    public User(String userName){
    	this.userName=userName;
  	}
    public User(String id, String userName, String userPass, String userBirthday, Integer sex, String phone,
			String email, Integer userType, String userImg, Integer questionId, String questionAnswer, Long carId,
			String created, String newvalue) {
		super();
		this.id = id;
		this.userName = userName;
		this.userPass = userPass;
		this.userBirthday = userBirthday;
		this.sex = sex;
		this.phone = phone;
		this.email = email;
		this.userType = userType;
		this.userImg = userImg;
		this.questionId = questionId;
		this.questionAnswer = questionAnswer;
		this.carId = carId;
		this.created = created;
		this.newvalue = newvalue;
	}

	/**
     * 获取用户id(UUID)
     * 
     * @return 用户id(UUID)
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置用户id(UUID)
     * 
     * @param id
     *          用户id(UUID)
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取用户名不能重复
     * 
     * @return 用户名不能重复
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * 设置用户名不能重复
     * 
     * @param userName
     *          用户名不能重复
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 获取用户密码
     * 
     * @return 用户密码
     */
    public String getUserPass() {
        return this.userPass;
    }

    /**
     * 设置用户密码
     * 
     * @param userPass
     *          用户密码
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * 获取生日
     * 
     * @return 生日
     */
    public String getUserBirthday() {
        return this.userBirthday;
    }

    /**
     * 设置生日
     * 
     * @param userBirthday
     *          生日
     */
    public void setUserBirthday(String userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * 获取性别
     * 
     * @return 性别
     */
    public Integer getSex() {
        return this.sex;
    }

    /**
     * 设置性别
     * 
     * @param sex
     *          性别
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * 获取用户手机号码
     * 
     * @return 用户手机号码
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * 设置用户手机号码
     * 
     * @param phone
     *          用户手机号码
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 获取用户邮箱
     * 
     * @return 用户邮箱
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * 设置用户邮箱
     * 
     * @param email
     *          用户邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 获取用户类型为1 管理员为999
     * 
     * @return 用户类型为1 管理员为999
     */
    public Integer getUserType() {
        return this.userType;
    }

    /**
     * 设置用户类型为1 管理员为999
     * 
     * @param userType
     *          用户类型为1 管理员为999
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * 获取用户头像
     * 
     * @return 用户头像
     */
    public String getUserImg() {
        return this.userImg;
    }

    /**
     * 设置用户头像
     * 
     * @param userImg
     *          用户头像
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

    /**
     * 获取用户密保问题
     * 
     * @return 用户密保问题
     */
    public Integer getQuestionId() {
        return this.questionId;
    }

    /**
     * 设置用户密保问题
     * 
     * @param questionId
     *          用户密保问题
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * 获取用户密保答案
     * 
     * @return 用户密保答案
     */
    public String getQuestionAnswer() {
        return this.questionAnswer;
    }

    /**
     * 设置用户密保答案
     * 
     * @param questionAnswer
     *          用户密保答案
     */
    public void setQuestionAnswer(String questionAnswer) {
        this.questionAnswer = questionAnswer;
    }

    /**
     * 获取用户购物车id
     * 
     * @return 用户购物车id
     */
    public Long getCarId() {
        return this.carId;
    }

    /**
     * 设置用户购物车id
     * 
     * @param carId
     *          用户购物车id
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }

    /**
     * 获取用户创建时间
     * 
     * @return 用户创建时间
     */
    public String getCreated() {
        return this.created;
    }

    /**
     * 设置用户创建时间
     * 
     * @param created
     *          用户创建时间
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     * 获取备用字段
     * 
     * @return 备用字段
     */
    public String getNewvalue() {
        return this.newvalue;
    }

    /**
     * 设置备用字段
     * 
     * @param newvalue
     *          备用字段
     */
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", userName=" + userName + ", userPass=" + userPass + ", userBirthday=" + userBirthday
				+ ", sex=" + sex + ", phone=" + phone + ", email=" + email + ", userType=" + userType + ", userImg="
				+ userImg + ", questionId=" + questionId + ", questionAnswer=" + questionAnswer + ", carId=" + carId
				+ ", created=" + created + ", newvalue=" + newvalue + "]";
	}
    
}